// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mcZLJjKLOAtitqRsifhSBCaRx0TGdrE',
    appId: '1:355873323204:web:82dd4e3441eb639dd67191',
    messagingSenderId: '355873323204',
    projectId: 'thrift-phone',
    authDomain: 'thrift-phone.firebaseapp.com',
    storageBucket: 'thrift-phone.firebasestorage.app',
    measurementId: 'G-3BCR8VHJ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwCb9gCUxWsezdKfUd75_QbWI3sQ1h4P0',
    appId: '1:355873323204:android:2779ac937fd066c3d67191',
    messagingSenderId: '355873323204',
    projectId: 'thrift-phone',
    storageBucket: 'thrift-phone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTQI4nH9fOt6EP8L6YHUNKGwjjS0ILI4',
    appId: '1:355873323204:ios:1bfc1891358b6ac6d67191',
    messagingSenderId: '355873323204',
    projectId: 'thrift-phone',
    storageBucket: 'thrift-phone.firebasestorage.app',
    iosBundleId: 'com.example.phoneThrift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkTQI4nH9fOt6EP8L6YHUNKGwjjS0ILI4',
    appId: '1:355873323204:ios:1bfc1891358b6ac6d67191',
    messagingSenderId: '355873323204',
    projectId: 'thrift-phone',
    storageBucket: 'thrift-phone.firebasestorage.app',
    iosBundleId: 'com.example.phoneThrift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0mcZLJjKLOAtitqRsifhSBCaRx0TGdrE',
    appId: '1:355873323204:web:b8c62027d6c070e6d67191',
    messagingSenderId: '355873323204',
    projectId: 'thrift-phone',
    authDomain: 'thrift-phone.firebaseapp.com',
    storageBucket: 'thrift-phone.firebasestorage.app',
    measurementId: 'G-G4TG15E87L',
  );
}
